asr:
  source_dir: speechbrain/asr-crdnn-rnnlm-librispeech
  save_dir: pretrained_models/asr-crdnn-rnnlm-librispeech

dataset:
  metadata_dir: /home/data/LibriSpeech/dev-clean.csv

denoiser:
  calculate: true
  use_pretrained_model: true
  pretrained_model_dir: dns64
  model_dir: dirpretrained_models/best.th
  repository_dir: denoiser
  noisy_dir: datasets/noisy
  clean_dir: datasets/clean

style_encoder:
  metadata_dir: /home/data/LibriSpeech/train-clean-100.csv
  # metadata_dir: /home/data/LibriSpeech/test-small.csv
  out_dir: outputs
  weight_dir: null

  lr: 3e-4
  batch_size: 32
  epochs: 100
  train_ratio: 0.8

wer_curve_experiment:
  snr_list: [0, 5, 10, 15, 20, 25, 30]
  root_dir: outputs/wer_curve_experiment